### ISSUE TITLE
I.sendPostRequest failed to post data

### ISSUE THREAD

**Issue by TechMaster** [PeterNgTr/codeceptjs-axios#1]
I used PostMan to REST. It works well.

However I used codeceptjs-axios and axios to post data, the REST server received blank data. I think there is a bug somewhere in codeceptjs-axios.

cocecept version 2.3.5

```javascript
Scenario('create new user', async (I) => {
  await I.sendPostRequest('/users', 
  {'name': ['X man'], 'email': ['xman@gmail.com'], 'pass': ['23123213']},
  {'Content-Type': 'application/json'});
});
```

**Comment by kobenguyent** [comment]
@TechMaster now you can use built-in REST helper of `codeceptjs` instead of this. https://codecept.io/helpers/REST#docsNav
